# `recipe.yaml` is the main configuration file for an MLflow Recipe.
# Required recipe parameters should be defined in this file with either concrete values or
# variables such as {{ INGEST_DATA_LOCATION }}.
#
# Variables must be dereferenced in a profile YAML file, located under `profiles/`.
# See `profiles/local.yaml` for example usage. One may switch among profiles quickly by
# providing a profile name such as `local` in the Recipe object constructor:
# `r = Recipe(profile="local")`
#
# NOTE: All "FIXME::REQUIRED" fields in recipe.yaml and profiles/*.yaml must be set correctly
#       to adapt this template to a specific regression problem. To find all required fields,
#       under the root directory of this recipe, type on a unix-like command line:
#       $> grep "# FIXME::REQUIRED:" recipe.yaml profiles/*.yaml
#
# NOTE: YAML does not support tabs for indentation. Please use spaces and ensure that all YAML
#       files are properly formatted.

recipe: "regression/v1"

target_col: "amount_in_usd"
#  Sets the primary metric to use to evaluate model performance. This primary
#                  metric is used to select best performing models in MLflow UI as well as in
#                  train and evaluation step.
#                  Built-in metrics are: example_count, mean_absolute_error, mean_squared_error,
#                  root_mean_squared_error, sum_on_label, mean_on_label, max_error,
#                  mean_absolute_percentage_error
primary_metric: "r2_score"
steps:
  # Specifies the dataset to use for model development
  ingest:
    using: "custom"
    location: "./data/Preprocessed_data.csv"
    loader_method: load_file_as_dataframe
  split:
    #
    # FAdjust the train/validation/test split ratios below.
    #
    split_ratios: [0.75, 0.125, 0.125]
    #
    #  Specifies the method to use to "post-process" the split datasets. Note that
    #                   arbitrary transformations should go into the transform step.
    post_split_filter_method: create_dataset_filter
  transform:
    using: "custom"
    #
    #  Specifies the method that defines an sklearn-compatible transformer, which
    #                   applies input feature transformation during model training and inference.
    transformer_method: transformer_fn
  train:
    #
    using: "custom"
    # Specifies the method that defines the estimator type and parameters to use for model training
    estimator_method: estimator_fn
  evaluate:
    #
    #
    validation_criteria:
      - metric: r2_score
        threshold: 0.9
  register:
    # Indicates whether or not a model that fails to meet performance thresholds should still
    # be registered to the MLflow Model Registry
    allow_non_validated_model: false
  # FIXME::OPTIONAL: Specify the dataset to use for batch scoring. All params serve the same function
  #                  as in `data`
  ingest_scoring:
    using: "custom"
    location: "./data/Preprocessed_data.csv"
    loader_method: load_file_as_dataframe
  predict:
    output:
      using: "custom"
      location: "./data/Preprocessed_data.csv"
      loader_method: load_file_as_dataframe
  #   model_uri: "models/model.pkl"
  #   result_type: "double"
  #   save_mode: "default
custom_metrics:
    - name: "r2_score"
      function: "get_custom_metrics"
      greater_is_better: True

